One CICD yaml file and auto prod setting at the end – azure #8

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -1,10 +1,41 @@
-name: cicd
+name: CICD of EasyScope Webapp
 
 on:
   push:
-    branches:
-      - main
+    branches: [ "main" ]
   pull_request:
+    branches: [ "main" ]
+
+jobs:
+  build:
+
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          cache: maven
+      - name: Build with Maven
+        run: mvn -B package --file pom.xml
+
+        # Run tests with debug and capture output
+      - name: Run Tests with Debug
+        run: mvn test -e -X || true
+
+        # Upload Surefire Reports in case of failure
+      - name: Upload Surefire Reports
+        if: failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: surefire-reports
+          path: target/surefire-reports
+
+on:
+  push:
     branches:
       - main
   workflow_dispatch:
@@ -14,55 +45,38 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      # Checkout repository
       - uses: actions/checkout@v4
 
-      # Set up Java version
       - name: Set up Java version
         uses: actions/setup-java@v4
         with:
           java-version: '17'
-          distribution: 'temurin'
-          cache: maven
+          distribution: 'microsoft'
 
-      # Build with Maven
       - name: Build with Maven
-        run: mvn clean install -DskipTests
+        run: mvn clean install
 
-      # Run tests with debug and capture output
-      - name: Run Tests with Debug
-        run: mvn test -e -X || true
-
-      # Upload Surefire Reports in case of failure
-      - name: Upload Surefire Reports
-        if: failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: surefire-reports
-          path: target/surefire-reports
-
-      # Upload JAR artifact
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
           name: java-app
-          path: target/*.jar
+          path: '${{ github.workspace }}/target/*.jar'
 
   deploy:
     runs-on: ubuntu-latest
     needs: build
-    env:
-      SPRING_PROFILES_ACTIVE: prod
+    environment:
+      name: 'Production'
+      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     permissions:
-      id-token: write
+      id-token: write #This is required for requesting the JWT
+
     steps:
-      # Download build artifact
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
         with:
           name: java-app
 
-      # Login to Azure
       - name: Login to Azure
         uses: azure/login@v2
         with:
@@ -70,7 +84,6 @@ jobs:
           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EF8C49E1AFED46F6BECF8DED76B5B267 }}
           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4188FF6A76C649B89EF485FEBE603E92 }}
 
-      # Deploy to Azure Web App ... it takes time ...
       - name: Deploy to Azure Web App
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v3
